site_name: Laravel Job Status
site_url: https://tobytwigger.github.io/laravel-job-status
repo_url: https://github.com/tobytwigger/laravel-job-status

nav:
    -   Getting Started: 'index.md'
    -   Tracking Jobs:
            -   Enabling: 'enable-tracking.md'
            -   Enhancing Jobs:
                    -   Progress: 'features/progress.md'
                    -   Sending messages: 'features/messages.md'
                    -   Signals: 'features/signals.md'
            -   Security: 'auth.md'
            -   Pruning: 'clearing.md'
    -   Job Dashboard:
            -   Installing: 'dashboard/installing.md'
            -   Viewing Jobs: 'dashboard/jobs.md'
            -   Viewing Runs: 'dashboard/runs.md'
            -   Viewing Batches: 'dashboard/batches.md'
            -   Security: 'dashboard/security.md'
#    -   Frontend:
#            -   Javascript Integration: 'js/custom-frontend.md'
#            -   Vue Integration: 'js/vue.md'
    -   Configuration: 'config.md'
    -   Advanced:
            -   Interacting with history programmatically: 'advanced/php-history.md'
theme:
    name: material
    custom_dir: overrides
    features:
        - navigation.instant
        - navigation.top
        - content.code.annotate
    palette:
        -   scheme: default
            media: "(prefers-color-scheme: dark)"
            toggle:
                icon: material/weather-night
                name: Switch to dark mode
        -   scheme: slate
            media: "(prefers-color-scheme: light)"
            toggle:
                icon: material/weather-sunny
                name: Switch to light mode

plugins:
    - search
    #  - with-pdf
    - git-authors
markdown_extensions:
    - admonition
    -   codehilite:
            guess_lang: true
            use_pygments: false
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - md_in_html
extra_css:
    - assets/highlight.css
    - assets/a11y-dark.css
    - assets/a11y-light.css
extra_javascript:
    - assets/highlight.js
    - assets/highlight_init.js
