site_name: Laravel Job Status
site_url: https://tobytwigger.github.io/laravel-job-status
repo_url: https://github.com/tobytwigger/laravel-job-status

nav:
    -   Getting Started: 'index.md'
    -   Enable tracking: 'tracking-jobs.md'
    -   Using tracking: 'retrieve-status.md'
    -   Tracking tools:
            -   Progress: 'progress.md'
            -   Sending messages: 'messages.md'
            -   Signals: 'signals.md'
    -   Protecting jobs: 'auth.md'
    -   Vue Integration: 'vue.md'
theme:
    name: material
    custom_dir: overrides
    features:
        - navigation.instant
        - navigation.top
    palette:
        -   scheme: default
            toggle:
                icon: material/weather-night
                name: Switch to dark mode
        -   scheme: slate
            toggle:
                icon: material/weather-sunny
                name: Switch to light mode

plugins:
    - search
    #  - with-pdf
    - git-authors
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
