site_name: Laravel Job Status
site_url: https://tobytwigger.github.io/laravel-job-status
repo_url: https://github.com/tobytwigger/laravel-job-status

nav:
    -   Getting Started: 'index.md'
    -   Enable tracking: 'tracking-jobs.md'
    -   Using tracking: 'retrieve-status.md'
    -   Tracking tools:
            -   Progress: 'progress.md'
            -   Sending messages: 'messages.md'
            -   Signals: 'signals.md'
    -   Protecting jobs: 'auth.md'
    - Frontend:
          - Vue Integration: 'vue.md'
          - Custom Frontend: 'custom-frontend.md'
theme:
    name: material
    custom_dir: overrides
    features:
        - navigation.instant
        - navigation.top
        - content.code.annotate
    palette:
        -   scheme: default
            media: "(prefers-color-scheme: dark)"
            toggle:
                icon: material/weather-night
                name: Switch to dark mode
        -   scheme: slate
            media: "(prefers-color-scheme: light)"
            toggle:
                icon: material/weather-sunny
                name: Switch to light mode

plugins:
    - search
    #  - with-pdf
    - git-authors
markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: true
          use_pygments: false
    - pymdownx.details
    - pymdownx.superfences
extra_css:
    - assets/highlight.css
    - assets/a11y-dark.css
    - assets/a11y-light.css
extra_javascript:
    - assets/highlight.js
    - assets/highlight_init.js
