name: Test build of laravel job status

on:
    push:
    pull_request:

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install dependencies
                if: steps.composer-cache.outputs.cache-hit != 'true'
                run: composer install --prefer-dist --no-progress --no-suggest


    build_php:
        needs: php-cs-fixer
        strategy:
            matrix:
                php: [ '8.1', '8.2' ]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install dependencies
                if: steps.composer-cache.outputs.cache-hit != 'true'
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: Run phpstan
                continue-on-error: true
                run: ./vendor/bin/phpstan analyze -c phpstan.neon

            -   name: Run test suite
                run: ./vendor/bin/paratest --coverage-clover ci/phpunit/clover.xml --coverage-html ci/phpunit/html

            -   name: Upload test coverage
                uses: actions/upload-artifact@v3
                with:
                    name: test-coverage
                    path: ci/phpunit/clover.xml

            -   name: Check test coverage
                uses: johanvanhelden/gha-clover-test-coverage-check@v1
                id: coverage
                with:
                    percentage: "50"
                    filename: "ci/phpunit/html"
                    rounded-precision: "0"
                    exit: false
