name: Static Analysis

on:
    workflow_dispatch:
    workflow_call:

jobs:
    phpstan-analysis:
        strategy:
            matrix:
                php: [ '8.1', '8.2' ]
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[CI]')"
        name: 🔎 Analyse the code for errors

        steps:
            -   name: ⏳ Check out repository
                uses: actions/checkout@v3
                with:
                    ref: ${{ github.ref }}

            -   name: ⏳ Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   name: ⏳ Setup Node
                uses: actions/setup-node@v3
                with:
                    node-version: 18

            -   name: ⏳ Install PHP dependencies
                uses: "ramsey/composer-install@v2"
                with:
                    composer-options: "--no-ansi --no-interaction --no-scripts --no-progress"

            -   name: ⏳ Install JS dependencies
                run: npm install
                working-directory: './dashboard'

            -   run: npm install -g @quasar/cli
                name: ⏳ Install the Quasar CLI

            -   name: 🔎 Analyse the PHP code with PHPStan
                uses: php-actions/phpstan@v3
                continue-on-error: true
                with:
                    path: config database routes src tests
                    php_version: ${{ matrix.php }}
                    error_format: github
                    memory_limit: 1G

            -   run: npm run lint
                working-directory: './dashboard'
                continue-on-error: true
                name: 🔎 Analyse the JS code
