name: PHPUnit Tests

on:
    workflow_dispatch:
    workflow_call:

jobs:
    phpunit-tests:
        strategy:
            matrix:
                php: [ '8.1', '8.2' ]
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: ${{ github.ref }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install dependencies
                if: steps.composer-cache.outputs.cache-hit != 'true'
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: Run test suite
                run: ./vendor/bin/paratest --coverage-clover ci/phpunit/clover.xml --coverage-html ci/phpunit/html --log-junit ci/phpunit/junit.xml

            -   name: Upload test coverage
                uses: actions/upload-artifact@v3
                with:
                    name: test-coverage
                    path: ci/phpunit/html

            -   name: Check test coverage
                uses: johanvanhelden/gha-clover-test-coverage-check@v1
                id: coverage
                with:
                    percentage: "50"
                    filename: ci/phpunit/clover.xml
                    rounded-precision: "0"
                    exit: false

            -   name: Publish Test Report
                uses: mikepenz/action-junit-report@v3
                if: always() # always run even if the previous step fails
                with:
                    report_paths: 'ci/phpunit/junit.xml'

            -   name: Upload test summary
                uses: actions/upload-artifact@v3
                with:
                    name: summary
                    path: "ci/phpunit/summary.md"
                if: always()

