name: Unit Testing & Static Analysis

on:
    pull_request:

jobs:
    php-linter:
        if: "!contains(github.event.head_commit.message, '[CI - PHP Linting]')"
        uses: ./.github/flows/linting.yml
        secrets: inherit
    run-tests:
        if: "!contains(github.event.head_commit.message, '[CI]')"
        uses: ./.github/flows/phpunit_tests.yml
        needs: [php-linter]
    static-analysis:
        if: "!contains(github.event.head_commit.message, '[CI]')"
        uses: ./.github/flows/phpstan_analysis.yml
        needs: [php-linter]
