name: Release assets and final test

on:
    push:
        branches:
            - 'main'
    workflow_dispatch:

jobs:
    run-tests:
        if: "!contains(github.event.head_commit.message, '[CI]')"
        uses: ./.github/workflows/phpunit_tests.yml
    static-analysis:
        if: "!contains(github.event.head_commit.message, '[CI]')"
        uses: ./.github/workflows/phpstan_analysis.yml
    build-docs:
        if: "!contains(github.event.head_commit.message, '[CI - JS Files]')"
        needs: [static-analysis, run-tests]
        uses: ./.github/workflows/build_docs.yml
    build-js:
        if: "!contains(github.event.head_commit.message, '[CI - JS Files]')"
        needs: [static-analysis, run-tests]
        uses: ./.github/workflows/build_javascript.yml
